MESSAGES = {
    "start": "Добро пожаловать в библиотечный бот!",
    "already_registered": "Вы уже зарегистрированы и вошли в систему.",
    "enter_name": "Введите ваше имя:",
    "enter_contact_data": "Введите ваши контактные данные:",
    "enter_reader_number": "Введите пароль:",
    "registration_success": "Вы успешно зарегистрированы!",
    "try_again": "Попробуйте зарегистрироваться снова.",
    "already_logged_in": "Вы уже вошли в систему.",
    "user_logged_in": "Вход выполнен. Добро пожаловать, {name}!",
    "login_failed": "Неправильное имя пользователя или пароль.",
    "login_required": "Пожалуйста, войдите в систему для использования этой команды.",
    "enter_search_query": "Введите запрос для поиска:",
    "book_title": "Название",
    "author": "Автор",
    "no_books_found": "По вашему запросу книги не найдены.",
    "enter_book_id": "Введите ID книги:",
    "invalid_book_id": "Пожалуйста, введите корректный ID книги (число).",
    "book_not_found": "Книга с таким ID не найдена.",
    "logged_out": "Вы вышли из системы.",
    "no_available_books": "Доступных книг для бронирования нет.",
    "enter_book_id_for_reservation": "Введите ID книги для бронирования:",
    "book_reserved_successfully": "Книга успешно забронирована. Вам необходимо вернуть книгу до {return_date}.",
    "reservation_failed": "Не удалось забронировать книгу.",
    "no_active_reservations": "У вас нет текущих бронирований.",
    "date": "Дата",
    "min_length_error": "{field_name} должно содержать минимум 2 символа.",
    "username": "Имя пользователя",
    "invalid_reader_number": "Номер читателя должен содержать минимум 2 символа.",
    "enter_genre_name": "Введите название нового жанра:",
    "genre_added_successfully": "Жанр '{genre_name}' успешно добавлен с ID {genre_id}.",
    "genre_add_failed": "Не удалось добавить жанр '{genre_name}'.",
    "enter_genre_id_to_delete": "Введите ID жанра, который нужно удалить:",
    "genre_deleted_successfully": "Жанр с ID {genre_id} успешно удален.",
    "enter_author_name": "Введите ФИО автора:",
    "author_added_successfully": "Автор '{author_name}' успешно добавлен с ID {author_id}.",
    "invalid_author_id": "Пожалуйста, введите корректный ID автора (число).",
    "author_deleted_successfully": "Автор с ID {author_id} успешно удален.",
    "enter_publisher_name": "Введите название издателя:",
    "publisher_added_successfully": "Издатель '{publisher_name}' успешно добавлен с ID {publisher_id}.",
    "invalid_publisher_id": "Пожалуйста, введите корректный ID издателя (число).",
    "publisher_deleted_successfully": "Издатель с ID {publisher_id} успешно удален.",
    "enter_department_name": "Введите название отдела:",
    "department_added_successfully": "Отдел '{department_name}' успешно добавлен с ID {department_id}.",
    "invalid_department_id": "Пожалуйста, введите корректный ID отдела (число).",
    "department_deleted_successfully": "Отдел с ID {department_id} успешно удален.",
    "staff_login_required": "Пожалуйста, войдите в систему как персонал для использования этой команды.",
    "enter_user_id": "Введите ID пользователя:",
    "enter_reservation_id": "Введите ID резервирования, которое вы хотите удалить:",
    "reservation_deleted_successfully": "Резервирование с ID {reservation_id} успешно удалено.",
    "enter_staff_name": "Введите имя сотрудника:",
    "staff_name": "Имя сотрудника",
    "staff_login_success": "Вход выполнен. Добро пожаловать, {staff_name}!",
    "staff_login_failed": "Неверное имя сотрудника.",
    "empty_field_error": "Поле {field_name} не может быть пустым.",
    "user_id": "ID пользователя",
    "reservation_id": "ID резервирования",
    "book_name": "Книга",
    "max_reservations_reached": "Не допускается иметь больше одного бронирования!"
}
